version: '3.1'

services:
    frontend:
        image: nginx:alpine
        container_name: frontend            
        hostname: frontend
        ports:
            - 80:80
        volumes: 
            - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
            - ./frontend:/usr/share/nginx/html
                
          


           
